name: curai_app_mobile
description: "CurAi is an innovative Smart Medical Appointment Booking System designed to simplify and enhance the process of scheduling medical appointments. This mobile application, built with Flutter, offers a seamless experience for users to search for doctors, book appointments, and receive personalized recommendations through an AI-powered chatbot."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4

# versions available, run `flutter pub outdated`.
dependencies:
  adaptive_theme: 
  auto_size_text: 
  cached_network_image: 
  collection: ^1.19.1
  connectivity_plus:
  cupertino_icons:
  dartz: 
  dio: 
  equatable:
  expansion_tile_card:
  firebase_core:
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_advanced_switch:
  flutter_bloc:
  flutter_dotenv:
  flutter_inappwebview: 
  flutter_local_notifications:
  flutter_localizations:
    sdk: flutter
  flutter_map: 
  flutter_native_splash:
  flutter_rating: 
  flutter_screenutil:
  flutter_svg: 
  flutter_timezone:
  flutter_tts:
  geocoding: 
  geolocator:
  get_it:
  hive:
  hive_flutter:
  http:
  image_picker:
  intl: 
  latlong2: 
  lock_orientation_screen:
  logger:
  path_provider: 
  permission_handler:
  pin_code_fields:
  pull_to_refresh:
  readmore:
  sentry_flutter:
  shared_preferences:
  skeletonizer:
  timezone:
  toastification: 
  translator:
  url_launcher:

dev_dependencies:
  build_runner:
  flutter_lints:
  flutter_test:
    sdk: flutter
  hive_generator:
  very_good_analysis:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/svg/payment/
    - assets/svg/layout/
    - assets/launcher/
    - assets/svg/social/
    - .env.prod
    - .env.dev
    - lang/en.json
    - lang/ar.json

  fonts:
    # arabic font
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
    # english font 
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        
